server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: nacos:8848
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
            - After=2021-09-18T19:44:00.000+08:00[Asia/Shanghai]
          filters:
            - AddRequestHeader=msg, Tomorrow is the day!
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/order/**
