server:
  port: 8081

spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PWD}
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848

# 使用 Eureka 时配置
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka

logging:
  level:
    org.example: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

# 供 PatternProperties 使用
pattern:
  name: 本地环境 LOCAL
  date-format: MM-dd HH:mm:ss:SSS
  env-shared-value: undefined