server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cloud_user?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PWD:123456}
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    org.example: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS