server:
  port: 8088

spring:
  application:
    name: order-service
  profiles:
    active:
      dev
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: ${MYSQL_PWD}
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.example: debug

eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka