server:
  port: 10086

spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: false         # In standalone mode, switch off the server's client side behavior
    fetch-registry: false